// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elpzbeohfcavnkorchwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVscHpiZW9oZmNhdm5rb3JjaHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTYwNDEsImV4cCI6MjA2MTY3MjA0MX0.zkkoS1Lah9uif64pDK35u4RpIbtbwdAFwQXDWGa56ck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);